#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*

# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: EXECUTE_COMPONENTS_TEMPLATE_TESTS
  value: true
- name: _TeamName
  value:  AspNetCore

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Components_Template_Test
    jobDisplayName: "Test: Blazor Templates Playwright tests on Linux"
    agentOs: Linux
    isAzDOTestingJob: true
    enablePublishTestResults: false
    timeoutInMinutes: 60
    steps:
    - script: git submodule update --init
      displayName: Update submodules
    - script: ./restore.sh
      displayName: Run restore.sh
    - script: .dotnet/dotnet build ./src/ProjectTemplates/test/Templates.Blazor.Tests -c $(BuildConfiguration) --no-restore
      displayName: Build
    - script: .dotnet/dotnet test ./src/ProjectTemplates/test/Templates.Blazor.Tests -c $(BuildConfiguration) --no-build
                 --results-directory $(Build.SourcesDirectory)/artifacts/TestResults/$(BuildConfiguration)/TemplateTests
      displayName: Run Template tests
